CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE air_quality_readings (
    id BIGSERIAL PRIMARY KEY,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    location geography(POINT, 4326) NOT NULL,
    pm25 DOUBLE PRECISION,
    pm10 DOUBLE PRECISION,
    no2 DOUBLE PRECISION,
    aqi_score INTEGER NOT NULL CHECK (aqi_score BETWEEN 0 AND 100),
    source VARCHAR(100) NOT NULL,
    recorded_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE green_zones (
    id BIGSERIAL PRIMARY KEY,
    osm_id BIGINT,
    name VARCHAR(255) NOT NULL,
    zone_type VARCHAR(20) NOT NULL CHECK (zone_type IN ('PARK', 'FOREST', 'SQUARE')),
    location geography(POINT, 4326) NOT NULL,
    area_m2 DOUBLE PRECISION,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hazard_objects (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    hazard_type VARCHAR(20) NOT NULL CHECK (hazard_type IN ('FACTORY', 'INCINERATOR', 'LANDFILL', 'TPP')),
    location geography(POINT, 4326) NOT NULL,
    description TEXT,
    source VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_air_quality_readings_location ON air_quality_readings USING GIST (location);
CREATE INDEX idx_green_zones_location ON green_zones USING GIST (location);
CREATE INDEX idx_hazard_objects_location ON hazard_objects USING GIST (location);
